name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get backend URL
        run: |
          BACKEND_URL=$(aws elbv2 describe-load-balancers \
            --region us-east-1 \
            --query "LoadBalancers[?DNSName=='a2cb481f9437c436d8dd4b3ac94248f7-686979025.us-east-1.elb.amazonaws.com'].DNSName" \
            --output text)

          echo "BACKEND_URL=$BACKEND_URL" >> "$GITHUB_ENV"

      - name: Build frontend Docker image
        working-directory: starter/frontend
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL="http://${BACKEND_URL}" \
            -t 356361756350.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }} \
            .

      - name: Push frontend Docker image
        run: |
          docker push \
            356361756350.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name cluster

      - name: Deploy frontend to EKS
        working-directory: starter
        run: |
          sed -i "s|image: .*frontend:.*|image: 356361756350.dkr.ecr.us-east-1.amazonaws.com/frontend:${{ github.sha }}|" frontend/k8s/deployment.yaml
          kubectl apply -k frontend/k8s
          kubectl rollout status deployment/frontend
